version: '3.8'

services:
  fivem-server:
    build: .
    container_name: fivem-server
    restart: unless-stopped
    ports:
      - "30120:30120/tcp"  # FiveM server port
      - "30120:30120/udp"  # FiveM server port (UDP)
      - "30121:30121/tcp"  # FiveM server query port
      - "30121:30121/udp"  # FiveM server query port (UDP)
    volumes:
      - ./serverdata:/serverdata/serverfiles
    environment:
      - SERVER_KEY=replace
      - GAME_CONFIG=server.cfg
    stdin_open: true
    tty: true

