services:
  fivem-server:
    image: ghcr.io/skriptzip/fivem-docker:latest
    container_name: fivem
    restart: on-failure
    environment:
      - LICENSE_KEY=${LICENSE_KEY}
      - ENABLE_WEBSOCKET=1
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "30121:30121" 
    volumes:
      - ./fivem-data:/config
    tty: true
  fivem-local-server:
    build:
      context: .
    container_name: fivem-local
    restart: on-failure
    environment:
      - LICENSE_KEY=${LICENSE_KEY}
      - ENABLE_WEBSOCKET=1
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "30121:30121" 
    volumes:
      - ./fivem-data:/config
    tty: true