services:
  fivem:
    image: ghcr.io/skriptzip/fivem-docker:latest
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/path/to/resources/folder:/config"
      # Enable a volume mount for txAdmin's data files
      # - "/path/to/txData/folder:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      # Allow txAdmin's webserver port to be accessible
      # - "40120:40120"
    environment:
      LICENSE_KEY: "license-key-here"